### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by haopXpycary** [ChandlerBent/padchat-python#3]
楼主，你看这样是不是能增加代码对windows的兼容性(windows似乎不支持\033)？
1.创建一个二维数组，数组中每个元素默认为0。
2.创建一个二维码，其中每一个点对应一个二维数组中的元素。遍历二维码上的每一个点，如果该点为黑色，该点所对应的元素保持不变(默认为0)；如果该点为白色，改变所对应元素为1。
3.将二维数组download到本地
4.通过　和█，根据二维数组对二维码进行描绘并且一次性print。

**Comment by ChandlerBent** [comment]
其实代码中是支持输出二维码到本地。
但由于比较少用，有对应逻辑，但没写上保存图片代码。
现已补上。
可通过重载方法
```python
    def event_qrcode(self, data):
        '''
        二维码事件
        :param data: 
        :return: 
        '''
        url = data.get('url')
        self._qrcode(url, style='img')
```

`self._qrcode` 中 `style` 目前接口两种形式：
* `img` 保存图片
* `terminal` 输出终端

最新commit已支持`img` 保存图片功能
